#!/bin/bash

COMMANDS_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))/commands

# Check pit is installed
[ $(command -v pit) ] || exit 1;

# Include commands
for cmd in $(find ${COMMANDS_DIR}/*); do
    source $cmd
done;
